---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
name: blue-niri-os
description: Universal Blue with Niri Wayland compositor.

# base-image: ghcr.io/ublue-os/base-main
# base-image: ghcr.io/ublue-os/bazzite
base-image: ghcr.io/ublue-os/sericea-main
image-version: 41 # latest is also supported if you want new updates ASAP

modules:
  - from-file: common/common-modules.yml
  - from-file: common/niri-modules.yml
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
