---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# Bump version 0.1
name: blue-niri-os
description: Universal Blue with Niri Wayland compositor.


# base-image: ghcr.io/ublue-os/base-main
# base-image: ghcr.io/ublue-os/bazzite
# base-image: ghcr.io/ublue-os/sericea-main
base-image: ghcr.io/ublue-os/sway-atomic
image-version: latest

modules:
  - from-file: common/common-modules.yml
  - from-file: common/niri-modules.yml
  - from-file: common/utility-modules.yml
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
