---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# Bump version 2025-09-12
name: blue-niri-os
description: Universal Blue with Niri Wayland compositor.


# base-image: ghcr.io/ublue-os/base-main
# base-image: ghcr.io/ublue-os/bazzite
# base-image: ghcr.io/ublue-os/sericea-main
# base-image: ghcr.io/ublue-os/sway-atomic-nvidia
# base-image: ghcr.io/ublue-os/sway-atomic-main
# Update 06/28/25
base-image: ghcr.io/ublue-os/sway-atomic-nvidia
image-version: latest

modules:
  - from-file: common/common-modules.yml
  - from-file: common/niri-modules.yml
  - from-file: common/utility-modules.yml
  - from-file: common/netbird-modules.yml
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
