---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# Bump version 2025-11-20
name: blue-niri-os
description: Universal Blue with Niri Wayland compositor.

# https://github.com/wayblueorg/wayblue
base-image: ghcr.io/wayblueorg/sway-nvidia-open-gdm
image-version: latest

# image-version: latest

modules:
  - from-file: common/common-modules.yml
  - from-file: common/niri-modules.yml
  - from-file: common/utility-modules.yml
  - from-file: common/netbird-modules.yml
  - type: rpm-ostree
    remove:
      - firefox
      - firefox-langpacks
      - alacritty
